# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f73c2080ff761111f788ee820e58aaba8baa63daef25c5a04310b61b0f80ef58b516d640b911fea8afd71cc91bd0cb426c5957b2a31f2cb0a8a645d20f00f415

test:
  secret_key_base: 4d9ad92571cbfbebf0a17c169c731a8daef45693c314d01d99f548573524c3aca3b3061eccdcdc1feabbd3c68e560d54fe74be3156f061e2d29bc5a569c26bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
